import { Search, Code2, PenTool, FileText, Edit3, Pencil, FolderTree, SearchCode, Terminal, GitBranch, CheckCircle, FolderSearch, Cpu } from 'lucide-react'

/** 工具名称 → 图标映射 */
export const TOOL_ICONS: Record<string, React.ReactNode> = {
  web_search: <Search size={13} />,
  code_execute: <Code2 size={13} />,
  ui_generate: <PenTool size={13} />,
  file_read: <FileText size={13} />,
  file_write: <Edit3 size={13} />,
  file_edit: <Pencil size={13} />,
  file_delete: <Edit3 size={13} />,
  multi_edit: <Pencil size={13} />,
  move_file: <FolderTree size={13} />,
  todo_write: <CheckCircle size={13} />,
  file_list: <FolderTree size={13} />,
  file_search: <SearchCode size={13} />,
  terminal_exec: <Terminal size={13} />,
  git_operations: <GitBranch size={13} />,
  code_lint: <CheckCircle size={13} />,
  project_context: <FolderSearch size={13} />,
  screen_capture: <Cpu size={13} />,
  browser_screenshot: <Search size={13} />,
  browser_navigate: <Search size={13} />,
  design_preview: <PenTool size={13} />,
  design_critique: <PenTool size={13} />,
  design_audit: <PenTool size={13} />,
  design_a11y: <PenTool size={13} />,
  design_color: <PenTool size={13} />,
  network_capture: <Search size={13} />,
  web_fetch: <Search size={13} />,
  web_research: <Search size={13} />
}

/** 工具名称 → 中文标签映射 */
export const TOOL_LABELS: Record<string, string> = {
  web_search: '联网搜索',
  code_execute: '代码执行',
  ui_generate: 'UI 生成',
  file_read: '读取文件',
  file_write: '写入文件',
  file_edit: '编辑文件',
  file_delete: '删除文件',
  multi_edit: '批量编辑',
  move_file: '移动文件',
  todo_write: '任务列表',
  file_list: '列出文件',
  file_search: '搜索文件',
  terminal_exec: '终端执行',
  git_operations: 'Git 操作',
  code_lint: '代码检查',
  project_context: '项目上下文',
  screen_capture: '屏幕截图',
  browser_screenshot: '浏览器截图',
  browser_navigate: '浏览器导航',
  design_preview: '设计预览',
  design_critique: '设计审查',
  design_audit: '质量审计',
  design_a11y: '无障碍检查',
  design_color: '颜色分析',
  network_capture: '网络抓包',
  web_fetch: '网页抓取',
  web_research: '深度研究'
}
